service: groanbot
frameworkVersion: ">=2.0.0 <3.0.0"

provider:
  name: aws
  runtime: go1.x
  region: ${env:AWS_DEFAULT_REGION, 'us-east-2'}
  stage: ${env:GROANBOT_BUILD_STAGE, 'prod'}
  memorySize: 192
  versionFunctions: false
  iamRoleStatementsInherit: true
  iamRoleStatements:
    - Effect: "Allow"
      Action: ssm:GetParameter
      Resource: arn:aws:ssm:${env:AWS_DEFAULT_REGION, 'us-east-2'}:${env:AWS_ACCOUNT_ID, '1111222233334444'}:parameter/groanbot/*

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  tweet:
    handler: bin/tweet
    events:
      - schedule: rate(1 hour)
    environment:
      APP_ENV: "production"
      TWITTER_SCREEN_NAME: "GroanBot"
      TWITTER_CONSUMER_KEY: "/groanbot/twitter_consumer_key"
      TWITTER_CONSUMER_SECRET: "/groanbot/twitter_consumer_secret"
      TWITTER_ACCESS_KEY: "/groanbot/twitter_access_key"
      TWITTER_ACCESS_SECRET: "/groanbot/twitter_access_secret"
      MAX_RETRIES: 10
      SKIP_PREVIOUS_TWEETS: 720
